### ISSUE TITLE
Using https://localhost:3000 doesn't work

### ISSUE THREAD

**Issue by stanleycyang** [analog-nico/passport-pinterest#1]
The `https` callback url doesn't work. How were you able to get around it?

**Comment by analog-nico** [comment]
Hi @stanleycyang, I solved it in my dev environment by implementing https on port 3001. It is a bit involved because you have to generate a certificate but the following blogpost walks you through: http://blog.mgechev.com/2014/02/19/create-https-tls-ssl-application-with-express-nodejs/

**Comment by stanleycyang** [comment]
Oh I see! So after you did this and authorized **pinterest** you were able to move it out of development mode => production?

**Comment by analog-nico** [comment]
Pinterest only allows https callback urls. In my case my production system is behind a load balancer that does SSL termination. That means Pinterest calls the https callback url and this call is converted to an internal http call between the load balancer and my app container. Thus I only need to use the https solution in my dev environment.

**Comment by stanleycyang** [comment]
Cool I've also forced SSL in development only and it now works :+1:

**Comment by analog-nico** [comment]
Awesome! :)
