### ISSUE TITLE
Pinterest Oauth URL and Scope is changed ...!!!!!!!

### ISSUE THREAD

**Issue by imtechieraj** [analog-nico/passport-pinterest#7]
Hello everyone,  recently pinterest Oauth url and scope is changed.      
       1. I tried to achieve Oauth using this module **(passport-pinterest)**.  But It's redirect to "https://api.pinterest.com/oauth" But actual url is "https://in.pinterest.com/oauth/". 
       2. Scope also changed. **passport-pinterest** module says,  scope: ['read_public', 'read_relationships']. I have mentioned new scope bellow : 
       
ads:read - Read access to advertising data
boards:read - Read access to public boards
boards:read_secret - Read access to secret boards
boards:write - Write access to create, update, or delete boards
boards:write_secret - Write access to create, update, or delete secret boards
pins:read - Read access to Pins
pins:read_secret - Read access to secret Pins
pins:write - Write access to create, update, or delete Pins
pins:write_secret - Write access to create, update, or delete secret Pins
user_accounts:read - Read access to user accounts

Source : [https://developers.pinterest.com/docs/api/v5/#section/OpenAPI-security-definitions](https://developers.pinterest.com/docs/api/v5/#section/OpenAPI-security-definitions)

My question is how to change new Oauth URL using passport module ?

**Comment by analog-nico** [comment]
You can easily overwrite this with the help of Passport’s standard options. `authorizationURL` is the one you look for in particular. But it may be the case that you may need to overwrite other defaults as well. Here are [all of them](https://github.com/analog-nico/passport-pinterest/blob/8439b4875a459b9e964ed2d67723ee0b41710ea1/lib/passport-pinterest/strategy.js#L73-L76) that are currently set.

And of course just pass the new scopes with the `scope` option.

**Comment by imtechieraj** [comment]
It's working .Thank you so much.
